### ISSUE TITLE
crash on invalid token

### ISSUE THREAD

**Issue by fuji246** [leslie-wang/fs-over-http#2]
```
ERRO[0027] invalid token                                
2018/07/24 22:24:48 http: panic serving 192.168.1.235:51373: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0x10cf7980)
        /home/pi/.gvm/gos/go1.9.6/src/net/http/server.go:1697 +0x9c
panic(0x3feb70, 0x61da18)
        /home/pi/.gvm/gos/go1.9.6/src/runtime/panic.go:491 +0x204
database/sql.(*DB).Close(0x0, 0x10c156e2, 0x9)
        /home/pi/.gvm/gos/go1.9.6/src/database/sql/sql.go:657 +0x18
main.(*Handler).listAssetsYearMonth(0x10c10e00, 0x626cc8, 0x10c97050, 0x10ca2e00)
        /home/pi/.gvm/pkgsets/go1.9.6/global/src/github.com/leslie-wang/fs-over-http/v2/asset.go:624 +0x6b0
main.(*Handler).(main.listAssetsYearMonth)-fm(0x626cc8, 0x10c97050, 0x10ca2e00)
        /home/pi/.gvm/pkgsets/go1.9.6/global/src/github.com/leslie-wang/fs-over-http/v2/handler.go:51 +0x34
net/http.HandlerFunc.ServeHTTP(0x10c0e998, 0x626cc8, 0x10c97050, 0x10ca2e00)
        /home/pi/.gvm/gos/go1.9.6/src/net/http/server.go:1918 +0x34
github.com/leslie-wang/fs-over-http/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0x10c620c0, 0x626cc8, 0x10c97050, 0x10ca2e00)
        /home/pi/.gvm/pkgsets/go1.9.6/global/src/github.com/leslie-wang/fs-over-http/vendor/github.com/gorilla/mux/mux.go:159 +0xa8
net/http.serverHandler.ServeHTTP(0x10ca2480, 0x626cc8, 0x10c97050, 0x10ca2d00)
        /home/pi/.gvm/gos/go1.9.6/src/net/http/server.go:2619 +0x74
net/http.(*conn).serve(0x10cf7980, 0x6272f8, 0x10d01020)
        /home/pi/.gvm/gos/go1.9.6/src/net/http/server.go:1801 +0x57c
created by net/http.(*Server).Serve
        /home/pi/.gvm/gos/go1.9.6/src/net/http/server.go:2720 +0x208

```

**Comment by leslie-wang** [comment]
fixed

**Comment by fuji246** [comment]
find the reason why the token is not valid. when updating token in db, it requires the device parameter as well, if not the update will fail silently.
